# This workflow will build and publish a package to npmjs when a version release is created
# https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-using-yarn

name: Publish Package to npmjs

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

env:
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@numbersprotocol'

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Publish to npm
        run: yarn publish --no-git-tag-version
        env:
          NODE_AUTH_TOKEN: ${{ env.NODE_AUTH_TOKEN }}